"use client";
import dynamic from "next/dynamic";
import {useEffect,useState} from "react";
const LeaflineScene=dynamic(()=>import("../components/LeaflineScene"),{ssr:false});
const sections=[
{id:"hero",eyebrow:"LEAFLINE EVENTS · CHENNAI",title:<>Every event begins<br/>with a <i>leaf of faith.</i></>,body:"From a first spark to the final standing ovation, we build experiences people can feel.",dark:true},
{id:"about",eyebrow:"01 · WHO WE ARE",title:<>We don't book moments.<br/><i>We build worlds.</i></>,body:"Born from a shared creative obsession, Leafline brings strategy, atmosphere and execution together under one roof.",dark:false},
{id:"mission",eyebrow:"02 · OUR MISSION",title:<>From the first spark<br/>to the <i>standing ovation.</i></>,body:"We turn ideas into immersive worlds, blending Tamil Nadu's character with the pulse of a modern event studio.",dark:true},
{id:"numbers",eyebrow:"03 · THE JOURNEY",title:<>Ideas that grew<br/>into <i>memories.</i></>,body:"Every project adds another leaf to the story.",dark:true,stats:[["100+","Experiences"],["50+","Brands & clients"],["10","Service areas"],["∞","Moments"]]},
{id:"services",eyebrow:"04 · WHAT WE DO",title:<>One team.<br/><i>Every detail.</i></>,body:"Strategy, venues, design, production, entertainment, gifting, guest management and marketing — end to end.",dark:false},
{id:"work",eyebrow:"05 · THE WORK",title:<>Your idea<br/>deserves a <i>stage.</i></>,body:"Corporate events. Weddings. Brand activations. Private celebrations. We shape the atmosphere around the story.",dark:true},
{id:"process",eyebrow:"06 · THE PROCESS",title:<>Simple conversations.<br/><i>Seamless execution.</i></>,body:"Tell us the idea. We shape it, plan it, confirm it with a 50% advance, then bring it to life.",dark:false},
{id:"quote",eyebrow:"07 · LET'S CREATE",title:<>Got an event<br/><i>in mind?</i></>,body:"Your idea. Your budget. Our creativity.",dark:true}
];
export default function Page(){const[progress,setProgress]=useState(0);const[active,setActive]=useState(0);useEffect(()=>{const onScroll=()=>{const max=document.documentElement.scrollHeight-innerHeight;const p=max>0?scrollY/max:0;setProgress(p);setActive(Math.min(sections.length-1,Math.floor(p*sections.length)))};onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);return <main className="site"><LeaflineScene progress={progress} active={active}/><div className="grain"/><header className="nav"><a href="#hero" className="logo"><span className="leaf-mark">◖</span><span>LEAFLINE</span><small>events</small></a><nav>{sections.slice(1,5).map(s=><a key={s.id} href={`#${s.id}`}>{s.eyebrow.split("· ")[1]}</a>)}</nav><a href="#quote" className="navCta">GET A QUOTE <span>↗</span></a></header><div className="progress"><span style={{transform:`scaleX(${progress})`}}/></div><div className="scrollLabel"><span>SCROLL TO MOVE THE LEAF</span><b>{String(active+1).padStart(2,"0")} / 08</b></div><div className="sections">{sections.map(s=><section id={s.id} className={`storySection ${s.dark?"dark":"light"}`} key={s.id}><div className="sectionInner"><div className="copy"><p className="eyebrow">{s.eyebrow}</p><h1>{s.title}</h1><p className="body">{s.body}</p>{s.stats&&<div className="stats">{s.stats.map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div>}{s.id==="services"&&<div className="chips"><span>Event Strategy</span><span>Venue + Logistics</span><span>Creative + Decor</span><span>Technical + AV</span><span>Entertainment</span><span>Gifting</span><span>Guest Management</span><span>Marketing</span></div>}{s.id==="process"&&<div className="steps"><span>01 · IDEA</span><span>02 · SHAPE</span><span>03 · PLAN</span><span>04 · 50% ADVANCE</span><span>05 · EXECUTE</span></div>}{s.id==="quote"&&<a className="button" href="https://wa.me/919600065771?text=Hi%20Leafline!%20I%20have%20an%20event%20I%27d%20like%20to%20discuss." target="_blank" rel="noreferrer">START ON WHATSAPP <span>↗</span></a>}</div></div></section>)}</div><footer><span>LEAFLINE EVENTS</span><span>Every event begins with a leaf of faith.</span><span>Chennai · India</span></footer></main>}
